# Generated by Django 5.2.17 on 2026-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpMaster',
            fields=[
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=10)),
                ('otp_datetime', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
