# Generated by Django 5.2.17 on 2026-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('service_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_group_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
