# Generated by Django 5.2.17 on 2026-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMaster',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
