from django.contrib import admin
from .models import Location, ServiceGroup, Service, LocationServiceMapping, VisitTypeMaster, PriceRateMaster, PriceRateMasterLocations, OfferMaster, OfferLocations, OfferServiceGroups, SlotMaster, Patient, SlotBookingMaster, SlotBookingDetails, SlotBookingMasterRemarks, ReportFilesDetails, ServiceFilesDetails

admin.site.register(Location)
admin.site.register(ServiceGroup)
admin.site.register(Service)
admin.site.register(LocationServiceMapping)
admin.site.register(VisitTypeMaster)
admin.site.register(PriceRateMaster)
admin.site.register(PriceRateMasterLocations)
admin.site.register(OfferMaster)
admin.site.register(OfferLocations)
admin.site.register(OfferServiceGroups)
admin.site.register(SlotMaster)
admin.site.register(Patient)
admin.site.register(SlotBookingMaster)
admin.site.register(SlotBookingDetails)
admin.site.register(SlotBookingMasterRemarks)
admin.site.register(ReportFilesDetails)
admin.site.register(ServiceFilesDetails)
