from django.db import models
from accounts.models import User

class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    location_name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True)

class ServiceGroup(models.Model):
    service_group_id = models.AutoField(primary_key=True)
    service_group_name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True)

class Service(models.Model):
    service_id = models.AutoField(primary_key=True)
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.CASCADE, db_column='service_group_id')
    service_name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True)

class LocationServiceMapping(models.Model):
    location_service_mapping_id = models.AutoField(primary_key=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, db_column='location_id')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, db_column='service_id')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    is_active = models.BooleanField(default=True, null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_date = models.DateTimeField(auto_now=True, null=True, blank=True)

class VisitTypeMaster(models.Model):
    visit_type_id = models.AutoField(primary_key=True)
    visit_type_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    trial_353 = models.CharField(max_length=255, null=True, blank=True)

class PriceRateMaster(models.Model):
    price_rate_id = models.AutoField(primary_key=True)
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.CASCADE, db_column='service_group_id', null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, db_column='service_id', null=True, blank=True)
    visit_type = models.ForeignKey(VisitTypeMaster, on_delete=models.CASCADE, db_column='visit_type_id', null=True, blank=True)
    effective_from_date = models.DateTimeField(null=True, blank=True)
    effective_to_date = models.DateTimeField(null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, db_column='location_id', null=True, blank=True)

class PriceRateMasterLocations(models.Model):
    id = models.AutoField(primary_key=True)
    price_rate = models.ForeignKey(PriceRateMaster, on_delete=models.CASCADE, db_column='price_rate_id')
    location = models.ForeignKey(Location, on_delete=models.CASCADE, db_column='location_id')
    price = models.IntegerField()

class OfferMaster(models.Model):
    offer_id = models.AutoField(primary_key=True)
    offer_name = models.CharField(max_length=200)
    offer_discount = models.IntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    registration_type_id = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='user_id', related_name='offers_created')
    effective_date_from = models.DateTimeField(null=True, blank=True)
    effective_date_to = models.DateTimeField(null=True, blank=True)
    offer_option_id = models.IntegerField(null=True, blank=True)
    offer_type = models.CharField(max_length=50, null=True, blank=True)
    is_all_locations = models.BooleanField(null=True, blank=True)
    is_all_services = models.BooleanField(null=True, blank=True)
    offer_for_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='offer_for_user_id', related_name='offers_received')

class OfferLocations(models.Model):
    offer_location_id = models.AutoField(primary_key=True)
    offer = models.ForeignKey(OfferMaster, on_delete=models.CASCADE, db_column='offer_id')
    location = models.ForeignKey(Location, on_delete=models.CASCADE, db_column='location_id')

class OfferServiceGroups(models.Model):
    offer_service_group_id = models.AutoField(primary_key=True)
    offer = models.ForeignKey(OfferMaster, on_delete=models.CASCADE, db_column='offer_id')
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.CASCADE, db_column='service_group_id')

class SlotMaster(models.Model):
    slot_id = models.AutoField(primary_key=True)
    slot_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    order_no = models.IntegerField(null=True, blank=True)

class Patient(models.Model):
    patient_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='user_id')
    patient_name = models.CharField(max_length=255, null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    alternate_mobile_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    patient_file_name = models.CharField(max_length=255, null=True, blank=True)
    patient_file_extension = models.CharField(max_length=10, null=True, blank=True)
    pin = models.CharField(max_length=50, null=True, blank=True)
    ref_no = models.CharField(max_length=50, null=True, blank=True)
    height = models.FloatField(null=True, blank=True)
    bmi = models.FloatField(null=True, blank=True)
    bp = models.CharField(max_length=50, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

class SlotBookingMaster(models.Model):
    slot_booking_id = models.AutoField(primary_key=True)
    slot = models.ForeignKey(SlotMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='slot_id')
    visit_type = models.ForeignKey(VisitTypeMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='visit_type_id')
    slot_type_id = models.IntegerField(null=True, blank=True)
    service_type_id = models.IntegerField(null=True, blank=True)
    service_provider = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_provider_id', related_name='service_provider_bookings')
    slot_booking_datetime = models.DateTimeField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    patient_name = models.CharField(max_length=255, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    alternate_mobile_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_group_id')
    payment_method = models.CharField(max_length=50, null=True, blank=True)
    prescription_filename = models.CharField(max_length=255, null=True, blank=True)
    extension = models.CharField(max_length=10, null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True, db_column='patient_id')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='user_id', related_name='user_bookings')
    service_filename = models.CharField(max_length=255, null=True, blank=True)
    service_extension = models.CharField(max_length=10, null=True, blank=True)
    report_filename = models.CharField(max_length=255, null=True, blank=True)
    report_extension = models.CharField(max_length=10, null=True, blank=True)
    upload_or_click_photo = models.CharField(max_length=50, null=True, blank=True)
    payment_status = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    price_rate = models.ForeignKey(PriceRateMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='price_rate_id')
    machine_id = models.IntegerField(null=True, blank=True)
    offer = models.ForeignKey(OfferMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='offer_id')
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True, db_column='location_id')
    is_active = models.BooleanField(default=True)
    external_id = models.IntegerField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    longitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    item_discount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    invoice_discount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    gross_amount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    booking_address = models.TextField(null=True, blank=True)
    start_datetime = models.DateTimeField(null=True, blank=True)
    end_datetime = models.DateTimeField(null=True, blank=True)
    start_latitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    start_longitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    end_latitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    end_longitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    technician_status = models.CharField(max_length=50, null=True, blank=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    order_id = models.CharField(max_length=100, null=True, blank=True)
    signature_id = models.CharField(max_length=100, null=True, blank=True)
    is_read = models.BooleanField(null=True, blank=True)

class SlotBookingDetails(models.Model):
    slot_booking_det_id = models.AutoField(primary_key=True)
    slot_booking = models.ForeignKey(SlotBookingMaster, on_delete=models.CASCADE, db_column='slot_booking_id', null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_type_id')
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_group_id')
    price = models.IntegerField(null=True, blank=True)
    price_rate = models.ForeignKey(PriceRateMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='price_rate_id')
    price_discount = models.IntegerField(null=True, blank=True)
    promocode = models.CharField(max_length=50, null=True, blank=True)
    offer = models.ForeignKey(OfferMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='offer_id')
    discount_percent = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

class SlotBookingMasterRemarks(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='user_id')
    remarks = models.TextField(null=True, blank=True)
    entry_datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    slot_booking = models.ForeignKey(SlotBookingMaster, on_delete=models.CASCADE, db_column='slot_booking_id', null=True, blank=True)

class ReportFilesDetails(models.Model):
    report_file_det_id = models.AutoField(primary_key=True)
    slot_booking_det = models.ForeignKey(SlotBookingDetails, on_delete=models.CASCADE, db_column='slot_booking_det_id', null=True, blank=True)
    report_filename = models.CharField(max_length=255, null=True, blank=True)
    report_extension = models.CharField(max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    slot_booking = models.ForeignKey(SlotBookingMaster, on_delete=models.CASCADE, db_column='slot_booking_id', null=True, blank=True)
    external_id = models.IntegerField(null=True, blank=True)

class ServiceFilesDetails(models.Model):
    service_file_det_id = models.AutoField(primary_key=True)
    slot_booking_det = models.ForeignKey(SlotBookingDetails, on_delete=models.CASCADE, db_column='slot_booking_det_id', null=True, blank=True)
    service_filename = models.CharField(max_length=255, null=True, blank=True)
    service_extension = models.CharField(max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    slot_booking = models.ForeignKey(SlotBookingMaster, on_delete=models.CASCADE, db_column='slot_booking_id', null=True, blank=True)
