# Generated by Django 5.2.17 on 2026-08-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('service_group', models.ForeignKey(db_column='service_group_id', on_delete=django.db.models.deletion.CASCADE, to='service_group.servicegroup')),
            ],
        ),
    ]
