from django.db import models
from users.models import User
from patients.models import Patient
from locations.models import Location
from service_group.models import ServiceGroup
from services.models import Service
from slots.models import SlotMaster

class SlotBookingMaster(models.Model):
    slot_booking_id = models.AutoField(primary_key=True)
    slot = models.ForeignKey(SlotMaster, on_delete=models.SET_NULL, null=True, blank=True, db_column='slot_id')
    slot_type_id = models.IntegerField(null=True, blank=True)
    service_type_id = models.IntegerField(null=True, blank=True)
    service_provider = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_provider_id', related_name='service_provider_bookings')
    slot_booking_datetime = models.DateTimeField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    patient_name = models.CharField(max_length=255, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=10, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    alternate_mobile_number = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_group_id')
    payment_method = models.CharField(max_length=50, null=True, blank=True)
    prescription_filename = models.CharField(max_length=255, null=True, blank=True)
    extension = models.CharField(max_length=10, null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True, blank=True, db_column='patient_id')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, db_column='user_id', related_name='user_bookings')
    service_filename = models.CharField(max_length=255, null=True, blank=True)
    service_extension = models.CharField(max_length=10, null=True, blank=True)
    report_filename = models.CharField(max_length=255, null=True, blank=True)
    report_extension = models.CharField(max_length=10, null=True, blank=True)
    upload_or_click_photo = models.CharField(max_length=50, null=True, blank=True)
    payment_status = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    machine_id = models.IntegerField(null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True, db_column='location_id')
    is_active = models.BooleanField(default=True)
    consent_given = models.BooleanField(default=False)
    external_id = models.IntegerField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    longitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    net_amount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    item_discount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    invoice_discount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    gross_amount = models.DecimalField(max_digits=18, decimal_places=2, null=True, blank=True)
    booking_address = models.TextField(null=True, blank=True)
    start_datetime = models.DateTimeField(null=True, blank=True)
    end_datetime = models.DateTimeField(null=True, blank=True)
    start_latitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    start_longitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    end_latitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    end_longitude = models.DecimalField(max_digits=18, decimal_places=10, null=True, blank=True)
    technician_status = models.CharField(max_length=50, null=True, blank=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    order_id = models.CharField(max_length=100, null=True, blank=True)
    signature_id = models.CharField(max_length=100, null=True, blank=True)
    is_read = models.BooleanField(null=True, blank=True)

class SlotBookingDetails(models.Model):
    slot_booking_det_id = models.AutoField(primary_key=True)
    slot_booking = models.ForeignKey(SlotBookingMaster, on_delete=models.CASCADE, db_column='slot_booking_id', null=True, blank=True)
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_type_id')
    service_group = models.ForeignKey(ServiceGroup, on_delete=models.SET_NULL, null=True, blank=True, db_column='service_group_id')
    price = models.IntegerField(null=True, blank=True)
    price_discount = models.IntegerField(null=True, blank=True)
    promocode = models.CharField(max_length=50, null=True, blank=True)
    discount_percent = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    service_filename = models.CharField(max_length=255, null=True, blank=True)
    service_extension = models.CharField(max_length=10, null=True, blank=True)
    report_filename = models.CharField(max_length=255, null=True, blank=True)
    report_extension = models.CharField(max_length=10, null=True, blank=True)
