# Generated by Django 5.2.17 on 2026-08-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRateMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rates', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRateMasterLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='locations.location')),
                ('price_rate_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_prices', to='price_rate_master.priceratemaster')),
            ],
        ),
    ]
