# Generated by Django 5.2.17 on 2026-08-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('patients', '0001_initial'),
        ('service_group', '0001_initial'),
        ('services', '0001_initial'),
        ('slots', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBookingMaster',
            fields=[
                ('slot_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_type_id', models.IntegerField(blank=True, null=True)),
                ('service_type_id', models.IntegerField(blank=True, null=True)),
                ('slot_booking_datetime', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('prescription_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('service_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('service_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('report_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('report_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_or_click_photo', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('item_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('invoice_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('booking_address', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('technician_status', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('service_group', models.ForeignKey(blank=True, db_column='service_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_group.servicegroup')),
                ('service_provider', models.ForeignKey(blank=True, db_column='service_provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider_bookings', to='users.user')),
                ('slot', models.ForeignKey(blank=True, db_column='slot_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.slotmaster')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookings', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='SlotBookingDetails',
            fields=[
                ('slot_booking_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_discount', models.IntegerField(blank=True, null=True)),
                ('promocode', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('service', models.ForeignKey(blank=True, db_column='service_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('service_group', models.ForeignKey(blank=True, db_column='service_group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_group.servicegroup')),
                ('slot_booking', models.ForeignKey(blank=True, db_column='slot_booking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.slotbookingmaster')),
            ],
        ),
    ]
