# Generated by Django 5.2.17 on 2026-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbookingmaster',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
