# Generated by Django 5.2.17 on 2026-08-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_slotbookingmaster_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbookingdetails',
            name='report_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='slotbookingdetails',
            name='report_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slotbookingdetails',
            name='service_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='slotbookingdetails',
            name='service_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
