# Generated by Django 5.2.17 on 2026-08-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('service_group', '0001_initial'),
        ('user_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_type', models.CharField(max_length=50)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='locations.location')),
                ('service_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='service_group.servicegroup')),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='user_type.usertype')),
            ],
        ),
    ]
