# Generated by Django 5.2.17 on 2026-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('offer_master', '0001_initial'),
        ('service_group', '0001_initial'),
        ('user_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='offermaster',
            name='service_group',
        ),
        migrations.RemoveField(
            model_name='offermaster',
            name='user_type',
        ),
        migrations.AddField(
            model_name='offermaster',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='offers', to='locations.location'),
        ),
        migrations.AddField(
            model_name='offermaster',
            name='service_group',
            field=models.ManyToManyField(blank=True, related_name='offers', to='service_group.servicegroup'),
        ),
        migrations.AddField(
            model_name='offermaster',
            name='user_type',
            field=models.ManyToManyField(blank=True, related_name='offers', to='user_type.usertype'),
        ),
    ]
